### ISSUE TITLE
Use model from SmartAmpPro

### ISSUE THREAD

**Issue by R0Wi** [GuitarML/NeuralPi#8]
Hi and first thank's for this really interesting project! I was wondering which model formats are currently supported by NeuralPI. If i got things right currently the black box modeling of an amp or distorsion pedal has to be done by https://github.com/Alec-Wright/Automated-GuitarAmpModelling. For me the workflow behind https://github.com/GuitarML/SmartAmpPro looks a lot easier so i asked myself if it's possible to train a model on my desktop machine using `SmartAmpPro` and then transferring it to my PI using the provided scripts in this repo?

Thank's for your feedback 😎

**Comment by mishushakov** [comment]
thanks for the feedback, glad you're taking part!

SmartAmpPro is using different machine learning architecture, therefor they're incompatible
see this medium post for explanation:
https://keyth72.medium.com/guitarml-faq-6b18abc1116c

i'd suggest to stick with the latest architecture ([Automated-GuitarAmpModelling](https://github.com/Alec-Wright/Automated-GuitarAmpModelling)), because it's the most performant and portable

those models can be run on Desktop with the [Chameleon plugin](https://github.com/GuitarML/Chameleon)

as for training, we have a more user-friendly fork available: https://github.com/GuitarML/Automated-GuitarAmpModelling

if you'd to stick with SmartAmpPro, you could probably cross-compile it for Raspberry Pi and load it on ElkOS instead of the built-in NeuralPi software (`NeuralPi.vst`)

hopefully this answers your questions

**Comment by mishushakov** [comment]
cool,
you can already control NeuralPi with OSC client, for example: [TouchOSC](https://hexler.net/touchosc), just connect it to the IP:Port as shown in the plugin

i'm not aware if anyone has attempted to train the models on the Pi, so it might be worth a try

if it works, we could publish a `apt` package and include (reference) all the required training dependencies + the `.vst` (or `.lv2` for that matter), so that training could be done in the plugin
